### PR TITLE
Redefines Guru Does It For You

### PR DESCRIPTION
**Pull request by MarijeP**
And also a little tweaking with spacing.

### CODE REVIEW

**Comment by MarijeP** [comment]
Why? Or maybe I'm not thinking of something. I made it so it can go now - invoicing info is hidden because that's waiting on your stuff. This can just go out and we can market at will.

**Comment by toast38coza** [comment]
Was just thinking of the screenshot of the chat in the app? .. but I'm happy to marge to master already .. not really any harm if someone sees it early.

**Comment by MarijeP** [comment]
Duh, you're right, sorry. I'll change the screenshot.

**Comment by MarijeP** [comment]
I can't think of a screenshot to change it to, without it looking worse. So, lets just wing it...

**Pull request merged**
